# Generated by Django 2.1.2 on 2018-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='rut',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
