# Generated by Django 2.1.2 on 2018-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20181123_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tecnico',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
