# Generated by Django 2.1.2 on 2018-12-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20181128_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
