# Generated by Django 2.1.2 on 2018-11-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_auto_20181128_2122'),
        ('empresa', '0004_auto_20181128_2122'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='nombreEmpresa',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombreTecnico',
        ),
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.tecnico'),
        ),
    ]
