# Generated by Django 2.1.2 on 2018-12-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_servicio_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='horaInicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='horaTermino',
            field=models.TimeField(),
        ),
    ]
