# Generated by Django 2.1.2 on 2018-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
